apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: blahaj-issuer
spec:
  acme:
    email: "letsencrypt.org@blahaj.sh"
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
