apiVersion: v2
name: traefik
description: Traefik Ingress
type: application
version: 21.0.0
appVersion: "v2.9.6"

dependencies:
  - name: traefik
    repository: https://helm.traefik.io/traefik
    version: 21.0.0
    alias: traefik
