apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-files
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2048Gi
  storageClassName: ""
