---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-wildcard
spec:
  secretName: gitlab-wildcard-cert
  commonName: gitlab.blahaj.sh
  dnsNames:
    - gitlab.blahaj.sh
    - "*.gitlab.blahaj.sh"
  issuerRef:
    name: blahaj-issuer
    kind: ClusterIssuer
    group: cert-manager.io
...