traefik:
  additionalArguments:
  - "--entryPoints.web.http.redirections.entryPoint.to=:443"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

  service:
    enabled: true
    type: LoadBalancer

