---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2048Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jellyfin
    name: media
  storageClassName: "local-path"
  capacity:
    storage: 2048Gi
  local:
    path: "/mnt/media"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
                - omori