---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2048Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: jellyfin
    name: music
  storageClassName: "local-path"
  capacity:
    storage: 2048Gi
  local:
    path: "/mnt/files/Music"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
                - omori