---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-cert
spec:
  secretName: vaultwarden-blahaj-cert
  commonName: vault.blahaj.sh
  dnsNames:
    - vault.blahaj.sh
  issuerRef:
    name: blahaj-issuer
    kind: ClusterIssuer
    group: cert-manager.io
...