global:
  https: true
  edition: ce
  hosts:
    domain: blahaj.sh
  ingress:
    class: helm-traefik-ingress
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    tls:
      secretName: gitlab-wildcard-cert
    configureCertmanager: false

  storageClass: longhorn-xfs

gitlab:
  upgradeCheck:
    enabled: false

  certmanager:
    install: false

  nginx-ingress:
    controller:
      extraArgs:
        workaround: issue 2487
    enabled: false

  gitlab:
    gitaly:
      persistence:
        storageClass: longhorn-xfs

  postgresql:
    # # The chart is not up to date, the documentation is wrong :)
    # https://github.com/bitnami/charts/blob/09ba1564fed3df4f1d94518edcb58aab1f75c827/bitnami/postgresql/templates/statefulset.yaml
    master:
      persistence:
        storageClass: longhorn-xfs

  minio:
    persistence:
      storageClass: longhorn-xfs

  redis:
    master:
      persistence:
        storageClass: longhorn-xfs

  prometheus:
    install: false