global:
  https: true
  edition: ce
  hosts:
    domain: blahaj.sh
  ingress:
    class: traefik
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    tls:
      secretName: gitlab-wildcard-cert
    configureCertmanager: false

gitlab:
  certmanager:
  install: false

  nginx-ingress:
    controller:
      extraArgs:
        workaround: issue 2487
    enabled: false

  gitlab:
    gitaly:
      persistence:
        storageClass: longhorn-cloud

  postgresql:
    persistence:
      storageClass: longhorn-clou

  minio:
    persistence:
      storageClass: longhorn-cloud

  redis:
    master:
      persistence:
        storageClass: longhorn-cloud

  prometheus:
    install: false