vaultwarden:
  image:
    repository: vaultwarden/server
    tag: testing
    pullPolicy: IfNotPresent

  env:
    SIGNUPS_ALLOWED: false
    INVITATIONS_ALLOWED: true
    DOMAIN: https://vault.blahaj.sh
    SMTP_HOST: blahaj.sh
    SMTP_FROM: no-reply@blahaj.sh
    WEB_VAULT_ENABLED: true
    ADMIN_TOKEN: "INITIAL_TOKEN_CHANGE_IN_UI"

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      kubernetes.io/tls-acme: "false"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    path: /
    hosts:
      - vault.blahaj.sh
    tls:
      - secretName: vaultwarden-blahaj-cert
        hosts:
          - vault.blahaj.sh
    pathType: Prefix

  persistence:
    enabled: true
    storageClass: "longhorn-xfs"
    accessMode: ReadWriteOnce
    size: 3200Mi
    mountPath: /data
    extraVolumes: []
