ingress:
  enabled: true
  hostname: vault.blahaj.sh
  class: traefik
  tls: true
  tlsSecret: vaultwarden-cert
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

storage:
  enabled: true
  size: 10Gi
  class: longhorn-replicated

webVaultEnabled: true

signupDomains: ["blahaj.sh"]
signupsVerify: false

domain: https://vault.blahaj.sh

smtp:
  host: blahaj.sh
  from: no-reply@blahaj.sh
  fromName: "Vaultwarden"

adminToken: "INITIAL_TOKEN_CHANGE_IN_UI" # For the love of god, change this in the UI.